export const OpenJob = [
    {
      id : 1,
      "Jobname" : "Frontend Developer",
      "location" : "Delhi,India",
      "AboutCosmicContent1": "VUPICO is a leading enterprise business and technology solutions partner for small, medium and large global customers, is seeking for experienced professionals, who thrive on challenge and desire to make a real difference. With an environment of extraordinary innovation and unprecedented growth, this is an exciting opportunity for a self-starter who enjoys working in a quality-oriented, fast-paced, team environment.",
      "AboutCosmicContent2": "Vupico is growing MNC, operating from Different locations (Japan, India, Singapore, Australia & USA) across the globe.",
      "Role":"Frontend Developer",
      "Primary Skill set": " Frontend Developer",
      "Secondary Skill set" : "Frontend Developer",
      "Experience" : "Frontend Developer",
      "Work Type" : "We do have Both (Permanent/Contract)",
      "Eligibility" : "B.tech /Post Graduate",
      "Responsibility1": "Connections (RFC, DB Connect, Flat File,ODP,..etc)",
      "Responsibility2": "Migration/Upgradation (Well Versed with Pre & Post Upgrade Activities)",
      "Responsibility3": "Should be capable enough to fix the PRD Issues promptly",
      "Responsibility4": "Well versed with Gap Analysis, Process Chains ( Regular & Archiving)",
      "Responsibility5": "Should be capable enough in streamlining the ETL Process",
      "Responsibility6": "Should have exposure on New Features on BW 7.x & BW/4 HANA",
      "GeneralExpectation1":"Best Practices to be followed while development & Performance Tuning",
      "GeneralExpectation2":"Deployment Options (Cloud, On Premise & Hybrid)",
      "GeneralExpectation3":"Good Exposure into Presales Activities and working on Proposals & Customer Presentations",
      "GeneralExpectation4":"Should be comfortable enough in working with SAP on Product Bugs or Key Issues",
      "GeneralExpectation5":"Should be strong enough in Extracting the Business requirements with Zero Ambiguity",
      "GeneralExpectation6":"Have perfect overview on S/4HANA & Embedded Analytics, Standard Business Contents & Rapid Deployment Solutions (RDS)",
    },
    {
        id : 2,
        "Jobname" : "Backend Developer",
        "location" : "Delhi,India",
        "AboutCosmicContent1": "VUPICO is a leading enterprise business and technology solutions partner for small, medium and large global customers, is seeking for experienced professionals, who thrive on challenge and desire to make a real difference. With an environment of extraordinary innovation and unprecedented growth, this is an exciting opportunity for a self-starter who enjoys working in a quality-oriented, fast-paced, team environment.",
        "AboutCosmicContent2": "Vupico is growing MNC, operating from Different locations (Japan, India, Singapore, Australia & USA) across the globe.",
        "Role":"Backend Developer",
        "Primary Skill set": " Backend Developer",
        "Secondary Skill set" : "Backend Developer",
        "Experience" : "Backend Developer",
        "Work Type" : "We do have Both (Permanent/Contract)",
        "Eligibility" : "B.tech /Post Graduate",
        "Responsibility1": "Connections (RFC, DB Connect, Flat File,ODP,..etc)",
        "Responsibility2": "Migration/Upgradation (Well Versed with Pre & Post Upgrade Activities)",
        "Responsibility3": "Should be capable enough to fix the PRD Issues promptly",
        "Responsibility4": "Well versed with Gap Analysis, Process Chains ( Regular & Archiving)",
        "Responsibility5": "Should be capable enough in streamlining the ETL Process",
        "Responsibility6": "Should have exposure on New Features on BW 7.x & BW/4 HANA",
        "GeneralExpectation1":"Best Practices to be followed while development & Performance Tuning",
        "GeneralExpectation2":"Deployment Options (Cloud, On Premise & Hybrid)",
        "GeneralExpectation3":"Good Exposure into Presales Activities and working on Proposals & Customer Presentations",
        "GeneralExpectation4":"Should be comfortable enough in working with SAP on Product Bugs or Key Issues",
        "GeneralExpectation5":"Should be strong enough in Extracting the Business requirements with Zero Ambiguity",
        "GeneralExpectation6":"Have perfect overview on S/4HANA & Embedded Analytics, Standard Business Contents & Rapid Deployment Solutions (RDS)",
    },
    {
        id : 3,
        "Jobname" : "Full Stack Developer",
        "location" : "Delhi,India",
        "AboutCosmicContent1": "VUPICO is a leading enterprise business and technology solutions partner for small, medium and large global customers, is seeking for experienced professionals, who thrive on challenge and desire to make a real difference. With an environment of extraordinary innovation and unprecedented growth, this is an exciting opportunity for a self-starter who enjoys working in a quality-oriented, fast-paced, team environment.",
        "AboutCosmicContent2": "Vupico is growing MNC, operating from Different locations (Japan, India, Singapore, Australia & USA) across the globe.",
        "Role":"Full Stack Developer",
        "Primary Skill set": " Full Stack Developer",
        "Secondary Skill set" : "Full Stack Developer",
        "Experience" : "Full Stack Developer",
        "Work Type" : "We do have Both (Permanent/Contract)",
        "Eligibility" : "B.tech /Post Graduate",
        "Responsibility1": "Connections (RFC, DB Connect, Flat File,ODP,..etc)",
        "Responsibility2": "Migration/Upgradation (Well Versed with Pre & Post Upgrade Activities)",
        "Responsibility3": "Should be capable enough to fix the PRD Issues promptly",
        "Responsibility4": "Well versed with Gap Analysis, Process Chains ( Regular & Archiving)",
        "Responsibility5": "Should be capable enough in streamlining the ETL Process",
        "Responsibility6": "Should have exposure on New Features on BW 7.x & BW/4 HANA",
        "GeneralExpectation1":"Best Practices to be followed while development & Performance Tuning",
        "GeneralExpectation2":"Deployment Options (Cloud, On Premise & Hybrid)",
        "GeneralExpectation3":"Good Exposure into Presales Activities and working on Proposals & Customer Presentations",
        "GeneralExpectation4":"Should be comfortable enough in working with SAP on Product Bugs or Key Issues",
        "GeneralExpectation5":"Should be strong enough in Extracting the Business requirements with Zero Ambiguity",
        "GeneralExpectation6":"Have perfect overview on S/4HANA & Embedded Analytics, Standard Business Contents & Rapid Deployment Solutions (RDS)",
    },
    {
        id : 4,
        "Jobname" : "Android Developer",
        "location" : "Delhi,India",
        "AboutCosmicContent1": "VUPICO is a leading enterprise business and technology solutions partner for small, medium and large global customers, is seeking for experienced professionals, who thrive on challenge and desire to make a real difference. With an environment of extraordinary innovation and unprecedented growth, this is an exciting opportunity for a self-starter who enjoys working in a quality-oriented, fast-paced, team environment.",
        "AboutCosmicContent2": "Vupico is growing MNC, operating from Different locations (Japan, India, Singapore, Australia & USA) across the globe.",
        "Role":"Android Developer",
        "Primary Skill set": " Android Developer",
        "Secondary Skill set" : "Android Developer",
        "Experience" : "Android Developer",
        "Work Type" : "We do have Both (Permanent/Contract)",
        "Eligibility" : "B.tech /Post Graduate",
        "Responsibility1": "Connections (RFC, DB Connect, Flat File,ODP,..etc)",
        "Responsibility2": "Migration/Upgradation (Well Versed with Pre & Post Upgrade Activities)",
        "Responsibility3": "Should be capable enough to fix the PRD Issues promptly",
        "Responsibility4": "Well versed with Gap Analysis, Process Chains ( Regular & Archiving)",
        "Responsibility5": "Should be capable enough in streamlining the ETL Process",
        "Responsibility6": "Should have exposure on New Features on BW 7.x & BW/4 HANA",
        "GeneralExpectation1":"Best Practices to be followed while development & Performance Tuning",
        "GeneralExpectation2":"Deployment Options (Cloud, On Premise & Hybrid)",
        "GeneralExpectation3":"Good Exposure into Presales Activities and working on Proposals & Customer Presentations",
        "GeneralExpectation4":"Should be comfortable enough in working with SAP on Product Bugs or Key Issues",
        "GeneralExpectation5":"Should be strong enough in Extracting the Business requirements with Zero Ambiguity",
        "GeneralExpectation6":"Have perfect overview on S/4HANA & Embedded Analytics, Standard Business Contents & Rapid Deployment Solutions (RDS)",
    },
    {
        id : 5,
        "Jobname" : "Quality Analysis(QA)",
        "location" : "Delhi,India",
        "AboutCosmicContent1": "VUPICO is a leading enterprise business and technology solutions partner for small, medium and large global customers, is seeking for experienced professionals, who thrive on challenge and desire to make a real difference. With an environment of extraordinary innovation and unprecedented growth, this is an exciting opportunity for a self-starter who enjoys working in a quality-oriented, fast-paced, team environment.",
        "AboutCosmicContent2": "Vupico is growing MNC, operating from Different locations (Japan, India, Singapore, Australia & USA) across the globe.",
        "Role":"Quality Analysis",
        "Primary Skill set": " Quality Analysis",
        "Secondary Skill set" : "Quality Analysis",
        "Experience" : "Quality Analysis",
        "Work Type" : "We do have Both (Permanent/Contract)",
        "Eligibility" : "B.tech /Post Graduate",
        "Responsibility1": "Connections (RFC, DB Connect, Flat File,ODP,..etc)",
        "Responsibility2": "Migration/Upgradation (Well Versed with Pre & Post Upgrade Activities)",
        "Responsibility3": "Should be capable enough to fix the PRD Issues promptly",
        "Responsibility4": "Well versed with Gap Analysis, Process Chains ( Regular & Archiving)",
        "Responsibility5": "Should be capable enough in streamlining the ETL Process",
        "Responsibility6": "Should have exposure on New Features on BW 7.x & BW/4 HANA",
        "GeneralExpectation1":"Best Practices to be followed while development & Performance Tuning",
        "GeneralExpectation2":"Deployment Options (Cloud, On Premise & Hybrid)",
        "GeneralExpectation3":"Good Exposure into Presales Activities and working on Proposals & Customer Presentations",
        "GeneralExpectation4":"Should be comfortable enough in working with SAP on Product Bugs or Key Issues",
        "GeneralExpectation5":"Should be strong enough in Extracting the Business requirements with Zero Ambiguity",
        "GeneralExpectation6":"Have perfect overview on S/4HANA & Embedded Analytics, Standard Business Contents & Rapid Deployment Solutions (RDS)",
    },
]
